### ISSUE TITLE
Please put a License for the Code

### ISSUE THREAD

**Issue by JohannesPaulHoffmann** [NathanSalapat/desert_life#3]
Good day,

can You please add a License for the Code, so I can use (legally, otherwise via a contract) this Mod on My (public) Server?

Thanks!

Yours sincerely from Germany,
Johannes

**Comment by NathanSalapat** [comment]
Added in https://github.com/NathanSalapat/desert_life/commit/c45c84c00e8c2ef2d1f219ac69f58283ed9fb4c1
